DROP TABLE IF EXISTS USER_DETAILS;  
CREATE TABLE USER_DETAILS (  
username VARCHAR(50)  PRIMARY KEY,  
password VARCHAR(50) NOT NULL,  
role VARCHAR(50) NOT NULL  
);  



INSERT INTO USER_DETAILS VALUES ('mahesh', 'mahesh123', 'ROLE_USER');    
INSERT INTO USER_DETAILS VALUES ('rahul', 'rahul123', 'ROLE_CUST');    
INSERT INTO USER_DETAILS VALUES ('hari', 'hari123', 'ROLE_ADMIN');
INSERT INTO USER_DETAILS VALUES ('siva', 'siva123', 'ROLE_EMP'); 
INSERT INTO USER_DETAILS VALUES ('harshali', 'harshali123', 'ROLE_ADMIN');    